### PR TITLE
Added japanese trans

### PR DESCRIPTION
**Pull request by hirokiky**
Thanks to Japanese translators. It's now well translated. 
How about to publish ja documents on djangoproject.com?
Or we need more translated text before published?

### CODE REVIEW

**Comment by claudep** [comment]
Nice ! The minimal threshold defined is to have the intro fully translated, which is reached for Japanese.

**Comment by hirokiky** [comment]
Thanks a lot!!!!!

**Comment by claudep** [comment]
In one hour or so, you should be able to access https://docs.djangoproject.com/ja/1.9/. Then please review at least the home page to see if your translations contain any formatting error which would result in strange formatting or untranslated result.

**Comment by hirokiky** [comment]
Of cause. thanks.

**Comment by hirokiky** [comment]
still waiting...

**Comment by claudep** [comment]
Yeah, sorry. I have no access to server logs to see what's going wrong. I'll have to ping buddies.

**Comment by hirokiky** [comment]
oh, really thank you.

**Comment by claudep** [comment]
@timgraham The Japanese translation doesn't build on dp.com, is this related to https://github.com/django/djangoproject.com/issues/627 ?

**Comment by timgraham** [comment]
I don't see recent errors in the logs. I think the delay is because I added an optimization to `update_docs` so that we don't rebuild the docs unless there's a new change in `django/docs` (https://github.com/django/djangoproject.com/commit/94f3b12740c70bc5ab7cd992584576f580ac1215). I pushed a docs commit to 1.9 about an hour ago, so hopefully we should see Japanense after the build for that change completes.

**Comment by hirokiky** [comment]
I see. Thank you timgraham and claudep! 
We are so looking forward to it.

**Comment by hirokiky** [comment]
It's available now! https://docs.djangoproject.com/ja/1.9/
thank you!!

**Comment by hirokiky** [comment]
Pages are generated, formatting and syntax looks OK. 
More translations are completed, I will create new PR.

**Pull request merged**
