### PR TITLE
Added initial Polish translations, solves #8

### PR DESCRIPTION
**Pull request by m-aciek**
In reference to #8 I'm adding Polish docs' translations fetched [from Transifex](https://www.transifex.com/django/django-docs/) to be published on [djangoproject.com](https://docs.djangoproject.com/en/stable/).
Credits goes to: @adamkal (2014), @adrian-antonczyk (2015), **Andrzej Udodik** (2013), @gbdlin (2016), @lukaszkoziara (2015), @hryniuk (2013), @m-aciek (2015, 2016), **p** (2014) and @tkajtoch (2016) (matches by names and e-mails, 90% sure).

zrzut ekranu z 2016-11-04 o 18 51 30

### CODE REVIEW

**Comment by claudep** [comment]
Thanks for the patch. Two things:
* I only commit fully translated files or files with a significant number of translations. In that case, I would take only the first four.
* I'm running `msgcat --no-location` before committing files, as this makes better diffs and smaller patches when updating. The script `https://github.com/django/django-docs-translations/blob/stable/1.10.x/manage_translations.py` does that automatically but you can do it manually as well.

**Comment by tkajtoch** [comment]
Please don't merge this commit. Many polish translations have grammar and style errors, we cannot allow to publish this.

**Comment by claudep** [comment]
You should see with the coordinator to appoint Reviewers in the Transifex team, so you can have a quality second-pass on translations.

**Comment by m-aciek** [comment]
Although we currently doesn't have any active reviewers, I, as an editor, have put an afford to assure the quality. @tkajtoch, could you point out some phrases that need improvement? Please remember that it will be updated along the way, as translations will improve.

@claudep Thank for your comments above, I'm working on fixes.

**Comment by tkajtoch** [comment]
@claudep I'll take a look to already translated part and review it. Do I need to contact polish translation coordinator or somebody of the core coordinators team?

@m-aciek I've seen a lot of incorrectly translated sentences.
For example:
```
+msgid ""
+"I can't log in. When I enter a valid username and password, it brings up the"
+" login page again, with a \"Please enter a correct username and password\" "
+"error."
+msgstr "Nie mogę się zalogować. Kiedy wprowadzam poprawne nazwę użytkownika i hasło, pokazuje się znów strona logowania, z błędem „Proszę wprowadzić poprawną nazwę użytkownika i hasło”."
```
This looks like a machine translation.

**Comment by m-aciek** [comment]
@claudep Not fully translated files removed, the rest made smaller with the script.

@tkajtoch I don't see your point in case of that phrase, it's correct. @angularcircle is coordinator of [Polish team](https://www.transifex.com/django/teams/17080/pl/). You can message him [through Transifex](https://www.transifex.com/user/messages/compose/angularcircle/).

**Comment by claudep** [comment]
The advantage of having reviewers in a team is that you can more easily track which string has been reviewed and which not. Of course, reviewers should only be experienced translators.
@m-aciek Thanks, the patch is now technically correct.

**Comment by claudep** [comment]
Is the discussion closed? Are there any pending review of Polish translations?

**Comment by m-aciek** [comment]
We've been working with @tkajtoch on strings so they are reviewed in part. Hopefully I will update the PO files this evening.

**Comment by tkajtoch** [comment]
@m-aciek @claudep I have a weekend off so I'll translate and will verify the last strings in the most important resources (index, intro, glossary, contents, faq). I propose that on Sunday evening when the translations will be completed, we'll make an update.

I've already translated and reviewed over 500 strings in two weeks.

**Comment by m-aciek** [comment]
Ok, the files are updated and ready to be added. I've added FAQ as it is translated in 72%.

**Pull request merged**
